services:
  
  countryapi:
    build:
      context: ./src/CountryApi
    ports:
      - "5001:5001"
      - "5002:5002"
    environment:
      - ASPNETCORE_URLS=http://+:5001;https://+:5002
  yarp-gateway:
    image: ${DOCKER_REGISTRY-}yarp-gateway
    build:
      context: ./src/YarpGateway
    ports:
      - "5000:80"
    depends_on:
      - countryapi